# Generated by Django 4.1.3 on 2022-12-02 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnoses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecordMedications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('sex', models.CharField(max_length=10)),
                ('breed', models.CharField(max_length=55)),
                ('age', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=25)),
                ('weight', models.IntegerField(default=0)),
                ('deceased', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_of_owner', to='retrieverapi.owners')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_of_that_species', to='retrieverapi.species')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenting_complaint', models.CharField(max_length=55)),
                ('subjective', models.TextField()),
                ('objective', models.TextField()),
                ('assessment', models.TextField()),
                ('plan', models.TextField()),
                ('date', models.DateField()),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_with_diagnosis', to='retrieverapi.diagnoses')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_written_by_doctor', to=settings.AUTH_USER_MODEL)),
                ('medications', models.ManyToManyField(through='retrieverapi.MedicalRecordMedications', to='retrieverapi.medications')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_for_patient', to='retrieverapi.patients')),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecordmedications',
            name='medical_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications_on_record', to='retrieverapi.medicalrecords'),
        ),
        migrations.AddField(
            model_name='medicalrecordmedications',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_with_medication', to='retrieverapi.medications'),
        ),
    ]
