# Generated by Django 4.1.3 on 2022-12-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retrieverapi', '0002_patients_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addendums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addendum', models.TextField()),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_addendums', to='retrieverapi.medicalrecords')),
            ],
        ),
    ]
