# Generated by Django 4.1.3 on 2022-12-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieverapi', '0003_addendums'),
    ]

    operations = [
        migrations.AddField(
            model_name='addendums',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
